# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HybridSynchAADL 
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://hybridsynchaadl.github.io" # the base hostname & protocol for the site
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: DOWNLOAD
      slug: /work
    - name: BENCHMARKS
      slug: /blog
    - name: DOCUMENTS
      slug: /work
    - name: PEOPLE

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: thkighie1224@postech.ac.kr
      link: mailto:thkighie1224@postech.ac.kr
    - name: Email
      value: ksron@postech.ac.kr 
      link: mailto:ksron@postech.ac.kr
    - name: Email
      value: kmbae@postech.ac.kr 
      link: mailto:kmbae@postech.ac.kr
    - name: Email
      value: peterol@ifi.uio.no 
      link: mailto:peterol@ifi.uio.no
    - name: Email
      value: masonkang@postech.ac.kr 
      link: mailto:masonkang@postech.ac.kr

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
