# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: HybridSynchAADL 
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://hybridsynchaadl.github.io/" # the base hostname & protocol for the site
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Download
      slug: /download
    - name: Benchmarks 
      slug: /benchmark
    - name: Documentation
      slug: /document
    - name: Artifact 
      slug: /artifact_cav2021

footer:
  show_powered_by: false
  contact:
    - name: Jaehun Lee
    - link: thkighie1224@postech.ac.kr

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
