load /Users/jaehun/Documents/HybridSynchAADL/maude/prelude.maude
load /Users/jaehun/Documents/HybridSynchAADL/maude/smt.maude
load ../semantics/interpreter-symbolic2-merge.maude
load ../instance/ThreeRoomTherm_simple_Instance-symbolic.maude
mod TEST-THREEROOMTHERM_SIMPLE_INSTANCE is
  including THREEROOMTHERM_SIMPLE_INSTANCE-MODEL-SYMBOLIC .
  including REACHABILITY-ANALYSIS .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initState : -> Object .
  eq initState = initialize(collapse(initial)) .
  
  eq loopBoundNum = 10 .
  eq transBoundNum = 10 .
  
  
  eq @m@ = ['TEST-THREEROOMTHERM_SIMPLE_INSTANCE] .
  
  op initial : -> PropSpec .
  eq initial = (((abs(((env1 | c[x] ) - [[42.0]])) < [[0.1]]) and (abs(((env2 | c[x] ) - [[49.48]])) < [[0.1]])) and (abs(((env3 | c[x] ) - [[32.19]])) < [[0.1]])) .
  op falseProp : -> PropSpec .
  eq falseProp = ((env1 | c[x] ) > [[5000.0]]) .
  
endm
	  
red reachAnalysis(
    initState,
    (ThreeRoomThermsimpleInstance | initial),
    ThreeRoomThermsimpleInstance | not(not(falseProp)),
    200
    ) .

quit
