load /Users/jaehun/Documents/HybridSynchAADL/maude/prelude.maude
load /Users/jaehun/Documents/HybridSynchAADL/maude/smt.maude
load ../semantics/interpreter-symbolic2-merge.maude
load ../instance/FourWaterTankSystem_simple_Instance-symbolic.maude
mod TEST-FOURWATERTANKSYSTEM_SIMPLE_INSTANCE is
  including FOURWATERTANKSYSTEM_SIMPLE_INSTANCE-MODEL-SYMBOLIC .
  including REACHABILITY-ANALYSIS .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initState : -> Object .
  eq initState = initialize(collapse(initial)) .
  
  eq loopBoundNum = 10 .
  eq transBoundNum = 10 .
  
  
  eq @m@ = ['TEST-FOURWATERTANKSYSTEM_SIMPLE_INSTANCE] .
  
  op initial : -> PropSpec .
  eq initial = ((((abs(((env1 | c[water] ) - [[55.0]])) < [[0.1]]) and (abs(((env2 | c[water] ) - [[38.5]])) < [[0.1]])) and (abs(((env3 | c[water] ) - [[44.0]])) < [[0.1]])) and (abs(((env4 | c[water] ) - [[40.0]])) < [[0.1]])) .
  op upperBound : -> PropSpec .
  eq upperBound = (((((env1 | c[water] ) >= [[30.0]]) and ((env2 | c[water] ) >= [[30.0]])) and ((env3 | c[water] ) >= [[30.0]])) and ((env4 | c[water] ) >= [[30.0]])) .
  
endm
	  
red reachAnalysis(
    initState,
    (FourWaterTankSystemsimpleInstance | initial),
    FourWaterTankSystemsimpleInstance | not(upperBound),
    400
    ) .

quit
