load /Users/jaehun/Documents/HybridSynchAADL/maude/prelude.maude
load /Users/jaehun/Documents/HybridSynchAADL/maude/smt.maude
load ../semantics/interpreter-symbolic2-merge.maude
load ../instance/ThreeWaterTankSystem_simple_Instance-symbolic.maude
mod TEST-THREEWATERTANKSYSTEM_SIMPLE_INSTANCE is
  including THREEWATERTANKSYSTEM_SIMPLE_INSTANCE-MODEL-SYMBOLIC .
  including REACHABILITY-ANALYSIS .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initState : -> Object .
  eq initState = initialize(collapse(initial)) .
  
  eq loopBoundNum = 10 .
  eq transBoundNum = 10 .
  
  
  eq @m@ = ['TEST-THREEWATERTANKSYSTEM_SIMPLE_INSTANCE] .
  
  op initial : -> PropSpec .
  eq initial = (((abs(((env1 | c[water] ) - [[55.0]])) < [[0.1]]) and (abs(((env2 | c[water] ) - [[40.0]])) < [[0.1]])) and (abs(((env3 | c[water] ) - [[40.0]])) < [[0.1]])) .
  op falseProp : -> PropSpec .
  eq falseProp = ((env1 | f[power] ) > [[1000.0]]) .
  
endm
	  
red reachAnalysis(
    initState,
    (ThreeWaterTankSystemsimpleInstance | initial),
    ThreeWaterTankSystemsimpleInstance | not(not(falseProp)),
    300
    ) .

quit
