
(omod DRONE-TEST is
  including SPEED-CONSENSUS-BEHAVIOR .
  including SYSTEM-BEHAVIOR .

  ops a b c d : -> Oid [ctor] .

  ops drone1 drone2 drone3 drone4 : -> Object .
  eq drone1
   = < a : Drone | speed : [4,0,4],
                   position : [0,0,0],
                   period : 2,
                   timer : 2,
                   buffer : empty,
                   neighbours : c > .

  eq drone2
  = < b : Drone | speed : [4,4,4],
                  position : [1,0,0],
                  period : 2,
                  timer : 2,
                  buffer : empty,
                  neighbours : a ; d  > .

  eq drone3
    = < c : Drone | speed : [4,4,0],
                    position : [0,0,1],
                    period : 2,
                    timer : 2,
                    buffer : empty,
                    neighbours : d > .

  eq drone4
    = < d : Drone | speed : [0,0,12],
                    position : [1,1,1],
                    period : 2,
                    timer : 2,
                    buffer : empty,
                    neighbours : b > .

  op A : -> Sys .
  eq A = {drone1 drone2 drone3 drone4} .

endom)

***(
(red obj .)
(red mte(obj) .)
(red delta(obj, 5/2) .)
(red delta(obj, 3) .)
(red delta(obj, 4) .)


(red msg .)
(red mte(msg) .)
(red deltaM(msg, 5/2) .)
(red deltaM(msg, 4) .)
(red deltaM(msg, 5) .)

set trace select on .
trace select tick .


set trace on .
set trace builtin off .
set trace select on .
trace select delta .
trace select mte .
--- trace select tick .

trace exclude META-LEVEL .
)
(red A .)


---(search [1] A =>* { < a : Drone | speed : T:Vector > < b : Drone | speed : T:Vector > < c : Drone | speed : T:Vector > < d : Drone | speed : T:Vector > Cnf:Configuration } .)
