load /Users/jaehun/Documents/HybridSynchAADL/maude/prelude.maude
load /Users/jaehun/Documents/HybridSynchAADL/maude/smt.maude
load ../semantics/interpreter-symbolic2-merge.maude
load ../instance/TwoDronesSystem_revu1D_Instance-symbolic.maude
mod TEST-TWODRONESSYSTEM_REVU1D_INSTANCE is
  including TWODRONESSYSTEM_REVU1D_INSTANCE-MODEL-SYMBOLIC .
  including REACHABILITY-ANALYSIS .
  including SPECIFICATION-LANGUAGE-SEMANTICS .

  op initState : -> Object .
  eq initState = initialize(collapse(initial)) .
  
  eq loopBoundNum = 10 .
  eq transBoundNum = 10 .
  
  
  eq @m@ = ['TEST-TWODRONESSYSTEM_REVU1D_INSTANCE] .
  
  op initial : -> PropSpec .
  eq initial = ((abs(((drone1 . environment | c[x] ) - [[0.0]])) < [[0.1]]) and (abs(((drone2 . environment | c[x] ) - [[0.5]])) < [[0.1]])) .
  op falseProp : -> PropSpec .
  eq falseProp = ((drone2 . environment | c[dotdotx] ) > [[1000.0]]) .
  
endm
	  
red reachAnalysis(
    initState,
    (TwoDronesSystemrevu1DInstance | initial),
    TwoDronesSystemrevu1DInstance | not(not(falseProp)),
    400
    ) .

quit
